<h2>Listado de usuarios</h2>

<a href="<?php echo APP_URL; ?>usuarios/add">Agregar usuario</a>

<table border="1">
	<tr>
		<th>ID</th>
		<th>Email</th>
		<th>Username</th>
		<th>Status</th>
		<th>Acción</th>
	</tr>
<?php foreach ($this->usuarios as $usuario): ?>
	<tr>
		<td><?php echo $usuario['id']; ?></td>
		<td><?php echo $usuario['email']; ?></td>
		<td><?php echo $usuario['username']; ?></td>
		<td><?php echo $usuario['status']; ?></td>
		<td>
			<a href="<?php echo APP_URL; ?>usuarios/edit/<?php echo $usuario['id']; ?>">Editar</a> | 
			<a href="<?php echo APP_URL; ?>usuarios/delete/<?php echo $usuario['id']; ?>"> Eliminar</a>
		</td>
	</tr>
<?php endforeach; ?>
</table>

